// Array de filmes

export const filmes = [
    {
      titulo: "O Resgate do Soldado Ryan",
      descricao: "Durante a Segunda Guerra Mundial, um grupo de soldados é enviado para resgatar um paraquedista.",
      imagem: "./assets/saving_private_ryan_poster.jpg",
      ano: 1998,
      diretor: "Steven Spielberg",
      trailer: "https://www.youtube.com/watch?v=zwhP5b4tD6g",
    },
    {
      titulo: "Coração Valente",
      descricao: "A história de William Wallace liderando os escoceses contra os ingleses.",
      imagem: "./assets/braveheart_poster.jpg",
      ano: 1995,
      diretor: "Mel Gibson",
      trailer: "https://www.youtube.com/watch?v=1NJO0jxBtMo",
    },
    {
      titulo: "1917",
      descricao: "Dois soldados recebem a missão de entregar uma mensagem vital durante a Primeira Guerra Mundial.",
      imagem: "./assets/1917_poster.jpg",
      ano: 2019,
      diretor: "Sam Mendes",
      trailer: "https://www.youtube.com/watch?v=qklLQ74DoQE",
    },
    {
      titulo: "Platoon",
      descricao: "Um jovem recruta enfrenta os horrores da guerra do Vietnã, enquanto lida com a moralidade em combate.",
      imagem: "./assets/platoon_poster.jpg",
      ano: 1986,
      diretor: "Oliver Stone",
      trailer: "https://www.youtube.com/watch?v=KvtT3UyhibQ",
    },
    {
      titulo: "T-34",
      descricao: "Um grupo de prisioneiros soviéticos usa um tanque para escapar de um campo de prisioneiros nazista.",
      imagem: "./assets/t34_poster.jpeg", 
      ano: 2018,
      diretor: "Aleksey Sidorov",
      trailer: "https://www.youtube.com/watch?v=D1UDvi5xL9w",
    },
    {
      titulo: "Dunkirk",
      descricao: "Soldados aliados cercados na praia de Dunkirk lutam para escapar da força inimiga.",
      imagem: "./assets/dunkirk_poster.jpg",
      ano: 2017,
      diretor: "Christopher Nolan",
      trailer: "https://www.youtube.com/watch?v=F-eMt3SrfFU",
    },
    {
      titulo: "The Thin Red Line",
      descricao: "Uma visão poética e introspectiva da Batalha de Guadalcanal durante a Segunda Guerra Mundial.",
      imagem: "./assets/thin_red_line_poster.jpg",
      ano: 1998,
      diretor: "Terrence Malick",
      trailer: "https://www.youtube.com/watch?v=mKl5_OxKBn8",
    },
    {
      titulo: "All Quiet on the Western Front",
      descricao: "Um jovem soldado alemão enfrenta os horrores da Primeira Guerra Mundial nas trincheiras.",
      imagem: "./assets/all_quiet_poster.jpg",
      ano: 2022,
      diretor: "Edward Berger",
      trailer: "https://www.youtube.com/watch?v=hf8EYbVxtCY",
    },
    {
      titulo: "Fury",
      descricao: "Uma tripulação de tanque americano luta contra as forças nazistas no final da Segunda Guerra Mundial.",
      imagem: "./assets/fury_poster.jpg",
      ano: 2014,
      diretor: "David Ayer",
      trailer: "https://www.youtube.com/watch?v=q94n3eWOWXM",
    },
    {
      titulo: "13 Hours",
      descricao: "Um pequeno grupo de soldados americanos defende um complexo diplomático na Líbia contra um ataque terrorista.",
      imagem: "./assets/13_hours_poster.png",
      ano: 2016,
      diretor: "Michael Bay",
      trailer: "https://www.youtube.com/watch?v=uTKacYwfE7Y",
    },
    {
      titulo: "O Soldado que Não Existiu",
      descricao: "A história de um plano militar britânico para enganar os nazistas durante a Segunda Guerra Mundial.",
      imagem: "./assets/soldado_que_nao_existiu_poster.jpg",
      ano: 2021,
      diretor: "John Madden",
      trailer: "https://www.youtube.com/watch?v=AEHfoltxsHQ",
    },
    {
      titulo: "Number 24",
      descricao: "A luta de um grupo de jovens durante a ocupação japonesa na China na Segunda Guerra Mundial.",
      imagem: "./assets/number_24_poster.jpeg",
      ano: 2019,
      diretor: "Ke Zhuang",
      trailer: "https://www.youtube.com/watch?v=OxMOpAeYxmw",
    },
    {
      titulo: "Stalingrad",
      descricao: "Uma visão épica da Batalha de Stalingrado, uma das batalhas mais importantes da Segunda Guerra Mundial.",
      imagem: "./assets/stalingrad_poster.jpg",
      ano: 2013,
      diretor: "Fedor Bondarchuk",
      trailer: "https://www.youtube.com/watch?v=fRbOx5OITP0",
    },
];
  